version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    networks:
      - internal

  backend:
    build: ./backend
    depends_on:
      - db
    networks:
      - internal

  frontend:
    build: ./frontend
    ports:
      - "8000:5000"
    depends_on:
      - backend
    networks:
      - internal

networks:
  internal:
    driver: bridge